[tools]
bun = "latest"
codex = "latest"
foundry = "latest"
neovim = "nightly"
node = "latest"
opencode = "latest"
rust = { version = "latest", components = "rust-analyzer" }

[tool_alias]
opencode = "npm:opencode-ai"

[settings]
idiomatic_version_file_enable_tools = []
