format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$character\
"""

[directory]
read_only = " "
style = "bold blue"

[git_commit]
tag_symbol = "  "