#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"

[features]
multi_agent = true
prevent_idle_sleep = true
apps = true
default_mode_request_user_input = true

[projects."/Users/jmederos/.dots"]
trust_level = "trusted"

[projects."/Users/jmederos/.codex"]
trust_level = "trusted"

[projects."/Users/jmederos/src/0x/0x-labs"]
trust_level = "trusted"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.xcode-tools]
args = ["mcpbridge"]
command = "xcrun"
enabled = false

[mcp_servers.xcodebuild]
args = ["-y", "xcodebuildmcp@latest", "mcp"]
command = "npx"
enabled = false
